// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UEFASwissFormatSelector.Services;

#nullable disable

namespace UEFASwissFormatSelector.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251003173933_Added_virtual_ScenarioInstance_to_DbModifiedDictionaryEntity")]
    partial class Added_virtual_ScenarioInstance_to_DbModifiedDictionaryEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UEFASwissFormatSelector.Models.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("742bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("a5300dfa-f995-4bb3-9e2e-009b85752995"),
                            Name = "Manchester City"
                        },
                        new
                        {
                            Id = new Guid("752bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("a5300dfa-f995-4bb3-9e2e-009b85752995"),
                            Name = "Liverpool"
                        },
                        new
                        {
                            Id = new Guid("762bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("a5300dfa-f995-4bb3-9e2e-009b85752995"),
                            Name = "Arsenal"
                        },
                        new
                        {
                            Id = new Guid("772bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("a5300dfa-f995-4bb3-9e2e-009b85752995"),
                            Name = "Manchester United"
                        },
                        new
                        {
                            Id = new Guid("782bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("a5300dfa-f995-4bb3-9e2e-009b85752995"),
                            Name = "Newcastle United"
                        },
                        new
                        {
                            Id = new Guid("792bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("a5300dfa-f995-4bb3-9e2e-009b85752995"),
                            Name = "West Ham United"
                        },
                        new
                        {
                            Id = new Guid("802bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("a5300dfa-f995-4bb3-9e2e-009b85752995"),
                            Name = "Aston Villa"
                        },
                        new
                        {
                            Id = new Guid("812bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("8bb21cd3-572c-4392-bf4d-29aa4cf58b06"),
                            Name = "Real Madrid"
                        },
                        new
                        {
                            Id = new Guid("822bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("8bb21cd3-572c-4392-bf4d-29aa4cf58b06"),
                            Name = "Barcelona"
                        },
                        new
                        {
                            Id = new Guid("832bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("8bb21cd3-572c-4392-bf4d-29aa4cf58b06"),
                            Name = "Atlético Madrid"
                        },
                        new
                        {
                            Id = new Guid("842bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("8bb21cd3-572c-4392-bf4d-29aa4cf58b06"),
                            Name = "Sevilla"
                        },
                        new
                        {
                            Id = new Guid("852bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("8bb21cd3-572c-4392-bf4d-29aa4cf58b06"),
                            Name = "Real Sociedad"
                        },
                        new
                        {
                            Id = new Guid("862bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("8bb21cd3-572c-4392-bf4d-29aa4cf58b06"),
                            Name = "Villarreal"
                        },
                        new
                        {
                            Id = new Guid("872bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("6321ef33-73b5-45f8-9927-9afb37f39844"),
                            Name = "Bayern Munich"
                        },
                        new
                        {
                            Id = new Guid("882bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("6321ef33-73b5-45f8-9927-9afb37f39844"),
                            Name = "Borussia Dortmund"
                        },
                        new
                        {
                            Id = new Guid("892bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("6321ef33-73b5-45f8-9927-9afb37f39844"),
                            Name = "Bayer Leverkusen"
                        },
                        new
                        {
                            Id = new Guid("902bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("6321ef33-73b5-45f8-9927-9afb37f39844"),
                            Name = "Union Berlin"
                        },
                        new
                        {
                            Id = new Guid("912bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("6321ef33-73b5-45f8-9927-9afb37f39844"),
                            Name = "RB Leipzig"
                        },
                        new
                        {
                            Id = new Guid("922bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("5dcf05a0-aeec-487e-bab1-10a4b4913ef3"),
                            Name = "Inter Milan"
                        },
                        new
                        {
                            Id = new Guid("932bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("5dcf05a0-aeec-487e-bab1-10a4b4913ef3"),
                            Name = "Juventus"
                        },
                        new
                        {
                            Id = new Guid("942bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("5dcf05a0-aeec-487e-bab1-10a4b4913ef3"),
                            Name = "AC Milan"
                        },
                        new
                        {
                            Id = new Guid("952bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("5dcf05a0-aeec-487e-bab1-10a4b4913ef3"),
                            Name = "Napoli"
                        },
                        new
                        {
                            Id = new Guid("962bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("5dcf05a0-aeec-487e-bab1-10a4b4913ef3"),
                            Name = "Roma"
                        },
                        new
                        {
                            Id = new Guid("972bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("5dcf05a0-aeec-487e-bab1-10a4b4913ef3"),
                            Name = "Lazio"
                        },
                        new
                        {
                            Id = new Guid("982bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39844"),
                            Name = "Olympique de Marseille"
                        },
                        new
                        {
                            Id = new Guid("992bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39844"),
                            Name = "Paris Saint-Germain"
                        },
                        new
                        {
                            Id = new Guid("002bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39844"),
                            Name = "Lyon"
                        },
                        new
                        {
                            Id = new Guid("012bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39844"),
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = new Guid("022bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39855"),
                            Name = "Benfica"
                        },
                        new
                        {
                            Id = new Guid("032bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39855"),
                            Name = "Porto"
                        },
                        new
                        {
                            Id = new Guid("042bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39855"),
                            Name = "Sporting CP"
                        },
                        new
                        {
                            Id = new Guid("052bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39866"),
                            Name = "Ajax"
                        },
                        new
                        {
                            Id = new Guid("062bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39866"),
                            Name = "Feyenoord"
                        },
                        new
                        {
                            Id = new Guid("072bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39877"),
                            Name = "Celtic"
                        },
                        new
                        {
                            Id = new Guid("082bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39888"),
                            Name = "Shakhtar Donetsk"
                        },
                        new
                        {
                            Id = new Guid("092bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39899"),
                            Name = "Galatasaray"
                        },
                        new
                        {
                            Id = new Guid("102bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39866"),
                            Name = "Red Star Belgrade"
                        },
                        new
                        {
                            Id = new Guid("112bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39877"),
                            Name = "Dinamo Zagreb"
                        },
                        new
                        {
                            Id = new Guid("122bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39888"),
                            Name = "Olympiacos"
                        },
                        new
                        {
                            Id = new Guid("132bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39899"),
                            Name = "Club Brugge"
                        },
                        new
                        {
                            Id = new Guid("142bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("2661ef33-73b5-45f8-9927-9bfb37f39899"),
                            Name = "Copenhagen"
                        },
                        new
                        {
                            Id = new Guid("152bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("1691ef33-73b5-45f8-9927-9bfb37f39899"),
                            Name = "Red Bull Salzburg"
                        },
                        new
                        {
                            Id = new Guid("162bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39899"),
                            Name = "Genk"
                        },
                        new
                        {
                            Id = new Guid("172bf86e-4f43-4465-9872-34f9b1281f8a"),
                            CountryId = new Guid("1961ef33-73b5-45f8-9927-9bfb37f39899"),
                            Name = "Sheriff Tiraspol"
                        });
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.ClubInPot", b =>
                {
                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PotId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClubId", "PotId");

                    b.HasIndex("PotId");

                    b.ToTable("ClubsInPot");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.ClubInScenarioInstance", b =>
                {
                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScenarioInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Ranking")
                        .HasColumnType("real");

                    b.HasKey("ClubId", "ScenarioInstanceId");

                    b.HasIndex("ScenarioInstanceId");

                    b.ToTable("ClubsInScenarioInstance");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbrevation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a5300dfa-f995-4bb3-9e2e-009b85752995"),
                            Abbrevation = "ENG",
                            Name = "England"
                        },
                        new
                        {
                            Id = new Guid("5dcf05a0-aeec-487e-bab1-10a4b4913ef3"),
                            Abbrevation = "ITA",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = new Guid("8bb21cd3-572c-4392-bf4d-29aa4cf58b06"),
                            Abbrevation = "ESP",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = new Guid("6321ef33-73b5-45f8-9927-9afb37f39844"),
                            Abbrevation = "GER",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39844"),
                            Abbrevation = "FRA",
                            Name = "France"
                        },
                        new
                        {
                            Id = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39855"),
                            Abbrevation = "POR",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39866"),
                            Abbrevation = "NED",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39877"),
                            Abbrevation = "SCO",
                            Name = "Scotland"
                        },
                        new
                        {
                            Id = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39888"),
                            Abbrevation = "UKR",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39899"),
                            Abbrevation = "TUR",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39866"),
                            Abbrevation = "SRB",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39877"),
                            Abbrevation = "CRO",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39888"),
                            Abbrevation = "GRE",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39899"),
                            Abbrevation = "BEL",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = new Guid("2661ef33-73b5-45f8-9927-9bfb37f39899"),
                            Abbrevation = "DEN",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = new Guid("1691ef33-73b5-45f8-9927-9bfb37f39899"),
                            Abbrevation = "BEL",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = new Guid("1961ef33-73b5-45f8-9927-9bfb37f39899"),
                            Abbrevation = "MOL",
                            Name = "Moldova"
                        });
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.DbModifiedDictionaryEntity<UEFASwissFormatSelector.Models.Club>", b =>
                {
                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DictionaryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScenarioInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DictionaryKey")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ObjectId", "DictionaryId", "ScenarioInstanceId");

                    b.HasIndex("ScenarioInstanceId")
                        .IsUnique();

                    b.ToTable("DbModifiedDictionaryEntity<Club>");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.DbModifiedDictionaryEntity<UEFASwissFormatSelector.Models.Pot>", b =>
                {
                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DictionaryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScenarioInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DictionaryKey")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ObjectId", "DictionaryId", "ScenarioInstanceId");

                    b.HasIndex("ScenarioInstanceId")
                        .IsUnique();

                    b.ToTable("DbModifiedDictionaryEntity<Pot>");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.Pot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsOpponentPot")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ScenarioInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioInstanceId");

                    b.ToTable("Pots");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.Scenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HomeAndAwayPerOpponent")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NumberOfGamesPerPot")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfPot")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfTeamsPerPot")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Scenarios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c5300dfa-f995-4bb3-9e2e-009b85752995"),
                            HomeAndAwayPerOpponent = false,
                            Name = "UEFA2425",
                            NumberOfGamesPerPot = 2,
                            NumberOfPot = 4,
                            NumberOfTeamsPerPot = 9
                        },
                        new
                        {
                            Id = new Guid("d5300dfa-f995-4bb3-9e2e-009b85752995"),
                            HomeAndAwayPerOpponent = true,
                            Name = "EPL",
                            NumberOfGamesPerPot = 19,
                            NumberOfPot = 1,
                            NumberOfTeamsPerPot = 20
                        },
                        new
                        {
                            Id = new Guid("92944679-54a6-4248-9bf8-e50e0774dedc"),
                            HomeAndAwayPerOpponent = false,
                            Name = "4-2-2",
                            NumberOfGamesPerPot = 2,
                            NumberOfPot = 2,
                            NumberOfTeamsPerPot = 4
                        },
                        new
                        {
                            Id = new Guid("e2e36700-16f6-44de-a5c3-6acf484655c3"),
                            HomeAndAwayPerOpponent = false,
                            Name = "3-2-4",
                            NumberOfGamesPerPot = 2,
                            NumberOfPot = 4,
                            NumberOfTeamsPerPot = 3
                        });
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.ScenarioInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("ScenarioInstances");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Services.ModifiedDictionary<System.Collections.Generic.IEnumerable<UEFASwissFormatSelector.Models.Pot>>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScenarioInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioInstanceId")
                        .IsUnique();

                    b.ToTable("ModifiedDictionary<IEnumerable<Pot>>");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Services.ModifiedDictionary<System.Collections.Generic.List<UEFASwissFormatSelector.Models.Club>>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScenarioInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioInstanceId")
                        .IsUnique();

                    b.ToTable("ModifiedDictionary<List<Club>>");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Services.ModifiedDictionary<System.Collections.Generic.List<string>>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScenarioInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioInstanceId")
                        .IsUnique();

                    b.ToTable("ModifiedDictionary<List<string>>");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.Club", b =>
                {
                    b.HasOne("UEFASwissFormatSelector.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.ClubInPot", b =>
                {
                    b.HasOne("UEFASwissFormatSelector.Models.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UEFASwissFormatSelector.Models.Pot", "Pot")
                        .WithMany("ClubsInPot")
                        .HasForeignKey("PotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Pot");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.ClubInScenarioInstance", b =>
                {
                    b.HasOne("UEFASwissFormatSelector.Models.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UEFASwissFormatSelector.Models.ScenarioInstance", "ScenarioInstance")
                        .WithMany("ClubsInScenarioInstance")
                        .HasForeignKey("ScenarioInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("ScenarioInstance");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.DbModifiedDictionaryEntity<UEFASwissFormatSelector.Models.Club>", b =>
                {
                    b.HasOne("UEFASwissFormatSelector.Models.ScenarioInstance", "ScenarioInstance")
                        .WithOne("DbMatchUps")
                        .HasForeignKey("UEFASwissFormatSelector.Models.DbModifiedDictionaryEntity<UEFASwissFormatSelector.Models.Club>", "ScenarioInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ScenarioInstance");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.DbModifiedDictionaryEntity<UEFASwissFormatSelector.Models.Pot>", b =>
                {
                    b.HasOne("UEFASwissFormatSelector.Models.ScenarioInstance", "ScenarioInstance")
                        .WithOne("DbOpponents")
                        .HasForeignKey("UEFASwissFormatSelector.Models.DbModifiedDictionaryEntity<UEFASwissFormatSelector.Models.Pot>", "ScenarioInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ScenarioInstance");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.Pot", b =>
                {
                    b.HasOne("UEFASwissFormatSelector.Models.ScenarioInstance", null)
                        .WithMany("Pots")
                        .HasForeignKey("ScenarioInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.ScenarioInstance", b =>
                {
                    b.HasOne("UEFASwissFormatSelector.Models.Scenario", "Scenario")
                        .WithMany()
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Services.ModifiedDictionary<System.Collections.Generic.IEnumerable<UEFASwissFormatSelector.Models.Pot>>", b =>
                {
                    b.HasOne("UEFASwissFormatSelector.Models.ScenarioInstance", null)
                        .WithOne("Opponents")
                        .HasForeignKey("UEFASwissFormatSelector.Services.ModifiedDictionary<System.Collections.Generic.IEnumerable<UEFASwissFormatSelector.Models.Pot>>", "ScenarioInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Services.ModifiedDictionary<System.Collections.Generic.List<UEFASwissFormatSelector.Models.Club>>", b =>
                {
                    b.HasOne("UEFASwissFormatSelector.Models.ScenarioInstance", null)
                        .WithOne("MatchUps")
                        .HasForeignKey("UEFASwissFormatSelector.Services.ModifiedDictionary<System.Collections.Generic.List<UEFASwissFormatSelector.Models.Club>>", "ScenarioInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Services.ModifiedDictionary<System.Collections.Generic.List<string>>", b =>
                {
                    b.HasOne("UEFASwissFormatSelector.Models.ScenarioInstance", null)
                        .WithOne("MatchUpSkeleton")
                        .HasForeignKey("UEFASwissFormatSelector.Services.ModifiedDictionary<System.Collections.Generic.List<string>>", "ScenarioInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.Pot", b =>
                {
                    b.Navigation("ClubsInPot");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.ScenarioInstance", b =>
                {
                    b.Navigation("ClubsInScenarioInstance");

                    b.Navigation("DbMatchUps");

                    b.Navigation("DbOpponents");

                    b.Navigation("MatchUpSkeleton");

                    b.Navigation("MatchUps");

                    b.Navigation("Opponents");

                    b.Navigation("Pots");
                });
#pragma warning restore 612, 618
        }
    }
}
