// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UEFASwissFormatSelector.Services;

#nullable disable

namespace UEFASwissFormatSelector.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250917112930_Modified_Delete_Behavior_For_ForeignKeys")]
    partial class Modified_Delete_Behavior_For_ForeignKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UEFASwissFormatSelector.Models.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4f62785f-c352-413f-ad79-2d0b0298595c"),
                            CountryId = new Guid("a5300dfa-f995-4bb3-9e2e-009b85752995"),
                            Name = "Manchester City"
                        },
                        new
                        {
                            Id = new Guid("5f6b4c5c-f4b7-4d29-b90a-e1f65411ba62"),
                            CountryId = new Guid("a5300dfa-f995-4bb3-9e2e-009b85752995"),
                            Name = "Liverpool"
                        },
                        new
                        {
                            Id = new Guid("64881335-75d7-48a5-86e7-9f28e01365f1"),
                            CountryId = new Guid("a5300dfa-f995-4bb3-9e2e-009b85752995"),
                            Name = "Arsenal"
                        },
                        new
                        {
                            Id = new Guid("3ebcc484-78b0-4937-a195-99387f9eebbe"),
                            CountryId = new Guid("a5300dfa-f995-4bb3-9e2e-009b85752995"),
                            Name = "Manchester United"
                        },
                        new
                        {
                            Id = new Guid("fd1e7ed7-ca34-4406-9dd1-acfd3b4ea1be"),
                            CountryId = new Guid("a5300dfa-f995-4bb3-9e2e-009b85752995"),
                            Name = "Newcastle United"
                        },
                        new
                        {
                            Id = new Guid("9ebb7650-690e-4131-8c69-42f371d2fce0"),
                            CountryId = new Guid("a5300dfa-f995-4bb3-9e2e-009b85752995"),
                            Name = "West Ham United"
                        },
                        new
                        {
                            Id = new Guid("5a900e84-6b16-460c-9526-bacc54f128fe"),
                            CountryId = new Guid("a5300dfa-f995-4bb3-9e2e-009b85752995"),
                            Name = "Aston Villa"
                        },
                        new
                        {
                            Id = new Guid("6c0a4991-ded4-4081-9f6a-e98aa642937a"),
                            CountryId = new Guid("8bb21cd3-572c-4392-bf4d-29aa4cf58b06"),
                            Name = "Real Madrid"
                        },
                        new
                        {
                            Id = new Guid("a00fb886-0d4e-4223-b339-852e8f065d96"),
                            CountryId = new Guid("8bb21cd3-572c-4392-bf4d-29aa4cf58b06"),
                            Name = "Barcelona"
                        },
                        new
                        {
                            Id = new Guid("32cd6936-6fd1-4b33-a86c-42bed801421c"),
                            CountryId = new Guid("8bb21cd3-572c-4392-bf4d-29aa4cf58b06"),
                            Name = "Atlético Madrid"
                        },
                        new
                        {
                            Id = new Guid("e24c54a6-bd01-46fb-8c59-13fd114b5c88"),
                            CountryId = new Guid("8bb21cd3-572c-4392-bf4d-29aa4cf58b06"),
                            Name = "Sevilla"
                        },
                        new
                        {
                            Id = new Guid("a8cc04fe-7093-4dc8-9647-6f747f08c6e3"),
                            CountryId = new Guid("8bb21cd3-572c-4392-bf4d-29aa4cf58b06"),
                            Name = "Real Sociedad"
                        },
                        new
                        {
                            Id = new Guid("4485bfd7-d3ab-497b-8366-2eb6d59e775e"),
                            CountryId = new Guid("8bb21cd3-572c-4392-bf4d-29aa4cf58b06"),
                            Name = "Villarreal"
                        },
                        new
                        {
                            Id = new Guid("f11cb337-0467-4968-a605-6a0538248c18"),
                            CountryId = new Guid("6321ef33-73b5-45f8-9927-9afb37f39844"),
                            Name = "Bayern Munich"
                        },
                        new
                        {
                            Id = new Guid("0f077216-aea0-4c1e-958a-c0a74e008680"),
                            CountryId = new Guid("6321ef33-73b5-45f8-9927-9afb37f39844"),
                            Name = "Borussia Dortmund"
                        },
                        new
                        {
                            Id = new Guid("f0b6fcbb-f049-4eb4-99c9-996d59e30a86"),
                            CountryId = new Guid("6321ef33-73b5-45f8-9927-9afb37f39844"),
                            Name = "Bayer Leverkusen"
                        },
                        new
                        {
                            Id = new Guid("eccaa54b-c918-4ef5-bcc1-840ad04aaefd"),
                            CountryId = new Guid("6321ef33-73b5-45f8-9927-9afb37f39844"),
                            Name = "Union Berlin"
                        },
                        new
                        {
                            Id = new Guid("f1115688-bc1e-4f21-9b4d-887973de9fdd"),
                            CountryId = new Guid("6321ef33-73b5-45f8-9927-9afb37f39844"),
                            Name = "RB Leipzig"
                        },
                        new
                        {
                            Id = new Guid("773886aa-d9ed-4788-9254-4ab508d18cc5"),
                            CountryId = new Guid("5dcf05a0-aeec-487e-bab1-10a4b4913ef3"),
                            Name = "Inter Milan"
                        },
                        new
                        {
                            Id = new Guid("6279bf3b-8d5f-41b0-a824-56660543d813"),
                            CountryId = new Guid("5dcf05a0-aeec-487e-bab1-10a4b4913ef3"),
                            Name = "Juventus"
                        },
                        new
                        {
                            Id = new Guid("cc7c1335-525a-477c-84a4-5031a1516e96"),
                            CountryId = new Guid("5dcf05a0-aeec-487e-bab1-10a4b4913ef3"),
                            Name = "AC Milan"
                        },
                        new
                        {
                            Id = new Guid("f66e3a42-8a4e-4b32-97ea-2774895e4b40"),
                            CountryId = new Guid("5dcf05a0-aeec-487e-bab1-10a4b4913ef3"),
                            Name = "Napoli"
                        },
                        new
                        {
                            Id = new Guid("d687162b-e734-40aa-a0ed-c4ec49439397"),
                            CountryId = new Guid("5dcf05a0-aeec-487e-bab1-10a4b4913ef3"),
                            Name = "Roma"
                        },
                        new
                        {
                            Id = new Guid("600cdb41-e3a0-45ef-b385-dba771a73a3f"),
                            CountryId = new Guid("5dcf05a0-aeec-487e-bab1-10a4b4913ef3"),
                            Name = "Lazio"
                        },
                        new
                        {
                            Id = new Guid("58f6a076-0d78-4b50-87a2-0a08f7f08877"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39844"),
                            Name = "Olympique de Marseille"
                        },
                        new
                        {
                            Id = new Guid("0b7ce159-08b3-4acf-bab6-6ec54e409006"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39844"),
                            Name = "Paris Saint-Germain"
                        },
                        new
                        {
                            Id = new Guid("6911a2fc-f938-4c86-892b-6d600a0ce3d1"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39844"),
                            Name = "Lyon"
                        },
                        new
                        {
                            Id = new Guid("2b2aeb74-4d9d-46fa-868d-64e4a75387ac"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39844"),
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = new Guid("41de5302-30fb-4c4d-9a95-ffa123da23e0"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39855"),
                            Name = "Benfica"
                        },
                        new
                        {
                            Id = new Guid("fa9d3998-e1cc-49fe-9fbc-7ded3aa5086a"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39855"),
                            Name = "Porto"
                        },
                        new
                        {
                            Id = new Guid("b9bba96f-f981-405b-ad42-c7edaa61060e"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39855"),
                            Name = "Sporting CP"
                        },
                        new
                        {
                            Id = new Guid("26f466fe-44d0-4967-a388-918b2829fe23"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39866"),
                            Name = "Ajax"
                        },
                        new
                        {
                            Id = new Guid("2a5b332b-7696-45a3-b3c2-f56f2e9659ba"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39866"),
                            Name = "Feyenoord"
                        },
                        new
                        {
                            Id = new Guid("71a854fe-243d-459b-bee9-16a81d73bc12"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39877"),
                            Name = "Celtic"
                        },
                        new
                        {
                            Id = new Guid("634d9e78-490d-48c4-94e1-0640ae206787"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39888"),
                            Name = "Shakhtar Donetsk"
                        },
                        new
                        {
                            Id = new Guid("1c5fc9f5-52d2-417b-a50e-664a227b946c"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39899"),
                            Name = "Galatasaray"
                        },
                        new
                        {
                            Id = new Guid("169cf9b9-6167-4b5c-881e-a8bf6f44df44"),
                            CountryId = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39866"),
                            Name = "Red Star Belgrade"
                        },
                        new
                        {
                            Id = new Guid("ab455e3e-1b64-4f82-9b64-ef41fa502e8f"),
                            CountryId = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39877"),
                            Name = "Dinamo Zagreb"
                        },
                        new
                        {
                            Id = new Guid("01fce158-fb5c-4229-8032-34fe92a816c6"),
                            CountryId = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39888"),
                            Name = "Olympiacos"
                        },
                        new
                        {
                            Id = new Guid("835cb674-d10b-4e1c-addf-9d5d1b701b0d"),
                            CountryId = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39899"),
                            Name = "Club Brugge"
                        },
                        new
                        {
                            Id = new Guid("06476627-43af-4ed6-a046-6d9e4b7dcae1"),
                            CountryId = new Guid("2661ef33-73b5-45f8-9927-9bfb37f39899"),
                            Name = "Copenhagen"
                        },
                        new
                        {
                            Id = new Guid("09ca7bea-1d2a-49a4-a568-bd68de0e95a5"),
                            CountryId = new Guid("1691ef33-73b5-45f8-9927-9bfb37f39899"),
                            Name = "Red Bull Salzburg"
                        },
                        new
                        {
                            Id = new Guid("856447ff-487a-469d-b01e-368989a8358a"),
                            CountryId = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39899"),
                            Name = "Genk"
                        },
                        new
                        {
                            Id = new Guid("b45c4027-36be-4db7-bcda-5421d4df3d04"),
                            CountryId = new Guid("1961ef33-73b5-45f8-9927-9bfb37f39899"),
                            Name = "Sheriff Tiraspol"
                        });
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.ClubInPot", b =>
                {
                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PotId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClubId", "PotId");

                    b.HasIndex("PotId");

                    b.ToTable("ClubsInPot");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.ClubInScenarioInstance", b =>
                {
                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScenarioInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Ranking")
                        .HasColumnType("real");

                    b.HasKey("ClubId", "ScenarioInstanceId");

                    b.HasIndex("ScenarioInstanceId");

                    b.ToTable("ClubsInScenarioInstance");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbrevation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a5300dfa-f995-4bb3-9e2e-009b85752995"),
                            Abbrevation = "ENG",
                            Name = "England"
                        },
                        new
                        {
                            Id = new Guid("5dcf05a0-aeec-487e-bab1-10a4b4913ef3"),
                            Abbrevation = "ITA",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = new Guid("8bb21cd3-572c-4392-bf4d-29aa4cf58b06"),
                            Abbrevation = "ESP",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = new Guid("6321ef33-73b5-45f8-9927-9afb37f39844"),
                            Abbrevation = "GER",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39844"),
                            Abbrevation = "FRA",
                            Name = "France"
                        },
                        new
                        {
                            Id = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39855"),
                            Abbrevation = "POR",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39866"),
                            Abbrevation = "NED",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39877"),
                            Abbrevation = "SCO",
                            Name = "Scotland"
                        },
                        new
                        {
                            Id = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39888"),
                            Abbrevation = "UKR",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39899"),
                            Abbrevation = "TUR",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39866"),
                            Abbrevation = "SRB",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39877"),
                            Abbrevation = "CRO",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39888"),
                            Abbrevation = "GRE",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39899"),
                            Abbrevation = "BEL",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = new Guid("2661ef33-73b5-45f8-9927-9bfb37f39899"),
                            Abbrevation = "DEN",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = new Guid("1691ef33-73b5-45f8-9927-9bfb37f39899"),
                            Abbrevation = "BEL",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = new Guid("1961ef33-73b5-45f8-9927-9bfb37f39899"),
                            Abbrevation = "MOL",
                            Name = "Moldova"
                        });
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.Pot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ScenarioInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioInstanceId");

                    b.ToTable("Pots");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.Scenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HomeAndAwayPerOpponent")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NumberOfGamesPerPot")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfPot")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfTeamsPerPot")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Scenarios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c5300dfa-f995-4bb3-9e2e-009b85752995"),
                            HomeAndAwayPerOpponent = false,
                            Name = "UEFA2425",
                            NumberOfGamesPerPot = 2,
                            NumberOfPot = 4,
                            NumberOfTeamsPerPot = 9
                        },
                        new
                        {
                            Id = new Guid("d5300dfa-f995-4bb3-9e2e-009b85752995"),
                            HomeAndAwayPerOpponent = true,
                            Name = "EPL",
                            NumberOfGamesPerPot = 19,
                            NumberOfPot = 1,
                            NumberOfTeamsPerPot = 20
                        },
                        new
                        {
                            Id = new Guid("92944679-54a6-4248-9bf8-e50e0774dedc"),
                            HomeAndAwayPerOpponent = false,
                            Name = "4-2-2",
                            NumberOfGamesPerPot = 2,
                            NumberOfPot = 2,
                            NumberOfTeamsPerPot = 4
                        },
                        new
                        {
                            Id = new Guid("e2e36700-16f6-44de-a5c3-6acf484655c3"),
                            HomeAndAwayPerOpponent = false,
                            Name = "3-2-4",
                            NumberOfGamesPerPot = 2,
                            NumberOfPot = 4,
                            NumberOfTeamsPerPot = 3
                        });
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.ScenarioInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("ScenarioInstances");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.Club", b =>
                {
                    b.HasOne("UEFASwissFormatSelector.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.ClubInPot", b =>
                {
                    b.HasOne("UEFASwissFormatSelector.Models.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UEFASwissFormatSelector.Models.Pot", "Pot")
                        .WithMany("ClubsInPot")
                        .HasForeignKey("PotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Pot");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.ClubInScenarioInstance", b =>
                {
                    b.HasOne("UEFASwissFormatSelector.Models.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UEFASwissFormatSelector.Models.ScenarioInstance", "ScenarioInstance")
                        .WithMany("ClubsInScenarioInstance")
                        .HasForeignKey("ScenarioInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("ScenarioInstance");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.Pot", b =>
                {
                    b.HasOne("UEFASwissFormatSelector.Models.ScenarioInstance", null)
                        .WithMany("Pots")
                        .HasForeignKey("ScenarioInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.ScenarioInstance", b =>
                {
                    b.HasOne("UEFASwissFormatSelector.Models.Scenario", "Scenario")
                        .WithMany()
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.Pot", b =>
                {
                    b.Navigation("ClubsInPot");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.ScenarioInstance", b =>
                {
                    b.Navigation("ClubsInScenarioInstance");

                    b.Navigation("Pots");
                });
#pragma warning restore 612, 618
        }
    }
}
