// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UEFASwissFormatSelector.Services;

#nullable disable

namespace UEFASwissFormatSelector.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250917111540_Added_SeedData")]
    partial class Added_SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UEFASwissFormatSelector.Models.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d379c3ed-71c6-472b-8c7a-957cbd2b0cf8"),
                            CountryId = new Guid("a5300dfa-f995-4bb3-9e2e-009b85752995"),
                            Name = "Manchester City"
                        },
                        new
                        {
                            Id = new Guid("aa4a8252-1a16-4cd3-b1cb-dc3a2c1eafe8"),
                            CountryId = new Guid("a5300dfa-f995-4bb3-9e2e-009b85752995"),
                            Name = "Liverpool"
                        },
                        new
                        {
                            Id = new Guid("2947fb15-3299-4d56-9a02-649adc0a769c"),
                            CountryId = new Guid("a5300dfa-f995-4bb3-9e2e-009b85752995"),
                            Name = "Arsenal"
                        },
                        new
                        {
                            Id = new Guid("894e3dd8-e8f1-4b67-b77e-ec4704dcd48d"),
                            CountryId = new Guid("a5300dfa-f995-4bb3-9e2e-009b85752995"),
                            Name = "Manchester United"
                        },
                        new
                        {
                            Id = new Guid("d040c9f2-61ae-46b6-b99d-e35113f08a73"),
                            CountryId = new Guid("a5300dfa-f995-4bb3-9e2e-009b85752995"),
                            Name = "Newcastle United"
                        },
                        new
                        {
                            Id = new Guid("dfeb48dd-1ffe-4c28-8256-ccc0c1c71b73"),
                            CountryId = new Guid("a5300dfa-f995-4bb3-9e2e-009b85752995"),
                            Name = "West Ham United"
                        },
                        new
                        {
                            Id = new Guid("c3e146b4-56a2-407c-bec0-26814392de96"),
                            CountryId = new Guid("a5300dfa-f995-4bb3-9e2e-009b85752995"),
                            Name = "Aston Villa"
                        },
                        new
                        {
                            Id = new Guid("486ee81a-8d8d-4209-98f6-131314b4e8d9"),
                            CountryId = new Guid("8bb21cd3-572c-4392-bf4d-29aa4cf58b06"),
                            Name = "Real Madrid"
                        },
                        new
                        {
                            Id = new Guid("eb2c4cb7-ded3-4439-a6b0-2cae70b89a29"),
                            CountryId = new Guid("8bb21cd3-572c-4392-bf4d-29aa4cf58b06"),
                            Name = "Barcelona"
                        },
                        new
                        {
                            Id = new Guid("bbf95577-e60b-4f66-a4eb-462fcec1faa2"),
                            CountryId = new Guid("8bb21cd3-572c-4392-bf4d-29aa4cf58b06"),
                            Name = "Atlético Madrid"
                        },
                        new
                        {
                            Id = new Guid("b490f6ec-6773-4cb9-b240-49cac63de507"),
                            CountryId = new Guid("8bb21cd3-572c-4392-bf4d-29aa4cf58b06"),
                            Name = "Sevilla"
                        },
                        new
                        {
                            Id = new Guid("4b5b09fe-f36d-49b3-acb9-176707256614"),
                            CountryId = new Guid("8bb21cd3-572c-4392-bf4d-29aa4cf58b06"),
                            Name = "Real Sociedad"
                        },
                        new
                        {
                            Id = new Guid("484de9e5-1d2e-4d89-afbd-3ad3e29c76ab"),
                            CountryId = new Guid("8bb21cd3-572c-4392-bf4d-29aa4cf58b06"),
                            Name = "Villarreal"
                        },
                        new
                        {
                            Id = new Guid("3ab6ee57-acca-4b62-ac9e-efd1b4fe4957"),
                            CountryId = new Guid("6321ef33-73b5-45f8-9927-9afb37f39844"),
                            Name = "Bayern Munich"
                        },
                        new
                        {
                            Id = new Guid("1b158596-f133-408b-9227-37ef58c267c4"),
                            CountryId = new Guid("6321ef33-73b5-45f8-9927-9afb37f39844"),
                            Name = "Borussia Dortmund"
                        },
                        new
                        {
                            Id = new Guid("a88ba145-4531-4a5f-96d5-ff5aa827d394"),
                            CountryId = new Guid("6321ef33-73b5-45f8-9927-9afb37f39844"),
                            Name = "Bayer Leverkusen"
                        },
                        new
                        {
                            Id = new Guid("ac060e1f-d569-4ea5-a79a-231a1b07f88b"),
                            CountryId = new Guid("6321ef33-73b5-45f8-9927-9afb37f39844"),
                            Name = "Union Berlin"
                        },
                        new
                        {
                            Id = new Guid("dbde8e16-504f-4df2-bdf9-2378018355c2"),
                            CountryId = new Guid("6321ef33-73b5-45f8-9927-9afb37f39844"),
                            Name = "RB Leipzig"
                        },
                        new
                        {
                            Id = new Guid("c4dc9d7a-489d-4819-a5b0-09f60e3c7e83"),
                            CountryId = new Guid("5dcf05a0-aeec-487e-bab1-10a4b4913ef3"),
                            Name = "Inter Milan"
                        },
                        new
                        {
                            Id = new Guid("286cdb2a-c302-4232-a611-9756ab091755"),
                            CountryId = new Guid("5dcf05a0-aeec-487e-bab1-10a4b4913ef3"),
                            Name = "Juventus"
                        },
                        new
                        {
                            Id = new Guid("30e96714-52a6-4a0f-a5e9-f72e152729fc"),
                            CountryId = new Guid("5dcf05a0-aeec-487e-bab1-10a4b4913ef3"),
                            Name = "AC Milan"
                        },
                        new
                        {
                            Id = new Guid("39ad2db5-44d1-49ba-8e17-91cb9f4d53b9"),
                            CountryId = new Guid("5dcf05a0-aeec-487e-bab1-10a4b4913ef3"),
                            Name = "Napoli"
                        },
                        new
                        {
                            Id = new Guid("b5ff4dde-ce33-4fd5-87d5-566cd76801bf"),
                            CountryId = new Guid("5dcf05a0-aeec-487e-bab1-10a4b4913ef3"),
                            Name = "Roma"
                        },
                        new
                        {
                            Id = new Guid("c8284cee-66a4-495d-8785-a5d2d349bdc2"),
                            CountryId = new Guid("5dcf05a0-aeec-487e-bab1-10a4b4913ef3"),
                            Name = "Lazio"
                        },
                        new
                        {
                            Id = new Guid("7ccd80ad-a891-45c9-bc4a-f15ffcb683c2"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39844"),
                            Name = "Olympique de Marseille"
                        },
                        new
                        {
                            Id = new Guid("6cd26890-2df3-451c-8761-014b615b3df1"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39844"),
                            Name = "Paris Saint-Germain"
                        },
                        new
                        {
                            Id = new Guid("1bbbdaa6-8cdc-40f6-bac5-344271b42a9b"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39844"),
                            Name = "Lyon"
                        },
                        new
                        {
                            Id = new Guid("3efdb9f7-2255-4e42-84bf-d2fb0e8b7253"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39844"),
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = new Guid("0a2171c0-78fa-4a4d-a5d6-fc77b0e4ad83"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39855"),
                            Name = "Benfica"
                        },
                        new
                        {
                            Id = new Guid("9e7b3294-d442-4d48-bc2b-09365ede430c"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39855"),
                            Name = "Porto"
                        },
                        new
                        {
                            Id = new Guid("c5cd6ce5-7479-4592-a84f-da8761d2bac0"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39855"),
                            Name = "Sporting CP"
                        },
                        new
                        {
                            Id = new Guid("cfc455e8-679c-475e-a97b-d9fc95369225"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39866"),
                            Name = "Ajax"
                        },
                        new
                        {
                            Id = new Guid("63554ced-a7ba-402f-b485-708f6eb1d42c"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39866"),
                            Name = "Feyenoord"
                        },
                        new
                        {
                            Id = new Guid("fecc1ada-d7b5-43ee-ab04-0f5f81a1e282"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39877"),
                            Name = "Celtic"
                        },
                        new
                        {
                            Id = new Guid("f0f8a133-f7b5-4958-a293-408e6d878c2f"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39888"),
                            Name = "Shakhtar Donetsk"
                        },
                        new
                        {
                            Id = new Guid("c6d32cd4-43a4-4f77-8f4a-7c86829363c5"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39899"),
                            Name = "Galatasaray"
                        },
                        new
                        {
                            Id = new Guid("81afdf8a-03c9-456d-b94b-b587b5ad61ba"),
                            CountryId = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39866"),
                            Name = "Red Star Belgrade"
                        },
                        new
                        {
                            Id = new Guid("3acff47e-3960-4ce4-aa18-adfe6fc3edc3"),
                            CountryId = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39877"),
                            Name = "Dinamo Zagreb"
                        },
                        new
                        {
                            Id = new Guid("5dada835-43b3-433a-bc01-deae6e680e58"),
                            CountryId = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39888"),
                            Name = "Olympiacos"
                        },
                        new
                        {
                            Id = new Guid("99302cb2-f757-4115-8b17-180a7b5cd381"),
                            CountryId = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39899"),
                            Name = "Club Brugge"
                        },
                        new
                        {
                            Id = new Guid("df2f8068-2cb1-407c-9dc6-8898a51cfa5f"),
                            CountryId = new Guid("2661ef33-73b5-45f8-9927-9bfb37f39899"),
                            Name = "Copenhagen"
                        },
                        new
                        {
                            Id = new Guid("c7d0a582-3844-4422-a515-4bcc88e732fd"),
                            CountryId = new Guid("1691ef33-73b5-45f8-9927-9bfb37f39899"),
                            Name = "Red Bull Salzburg"
                        },
                        new
                        {
                            Id = new Guid("e5ddabc8-1493-4bc0-9f06-435e83b61b91"),
                            CountryId = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39899"),
                            Name = "Genk"
                        },
                        new
                        {
                            Id = new Guid("a37ab947-16d0-48db-b867-986b64102b0e"),
                            CountryId = new Guid("1961ef33-73b5-45f8-9927-9bfb37f39899"),
                            Name = "Sheriff Tiraspol"
                        });
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.ClubInPot", b =>
                {
                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PotId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClubId", "PotId");

                    b.HasIndex("PotId");

                    b.ToTable("ClubsInPot");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.ClubInScenarioInstance", b =>
                {
                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScenarioInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Ranking")
                        .HasColumnType("real");

                    b.HasKey("ClubId", "ScenarioInstanceId");

                    b.HasIndex("ScenarioInstanceId");

                    b.ToTable("ClubsInScenarioInstance");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbrevation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a5300dfa-f995-4bb3-9e2e-009b85752995"),
                            Abbrevation = "ENG",
                            Name = "England"
                        },
                        new
                        {
                            Id = new Guid("5dcf05a0-aeec-487e-bab1-10a4b4913ef3"),
                            Abbrevation = "ITA",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = new Guid("8bb21cd3-572c-4392-bf4d-29aa4cf58b06"),
                            Abbrevation = "ESP",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = new Guid("6321ef33-73b5-45f8-9927-9afb37f39844"),
                            Abbrevation = "GER",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39844"),
                            Abbrevation = "FRA",
                            Name = "France"
                        },
                        new
                        {
                            Id = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39855"),
                            Abbrevation = "POR",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39866"),
                            Abbrevation = "NED",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39877"),
                            Abbrevation = "SCO",
                            Name = "Scotland"
                        },
                        new
                        {
                            Id = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39888"),
                            Abbrevation = "UKR",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39899"),
                            Abbrevation = "TUR",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39866"),
                            Abbrevation = "SRB",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39877"),
                            Abbrevation = "CRO",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39888"),
                            Abbrevation = "GRE",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39899"),
                            Abbrevation = "BEL",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = new Guid("2661ef33-73b5-45f8-9927-9bfb37f39899"),
                            Abbrevation = "DEN",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = new Guid("1691ef33-73b5-45f8-9927-9bfb37f39899"),
                            Abbrevation = "BEL",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = new Guid("1961ef33-73b5-45f8-9927-9bfb37f39899"),
                            Abbrevation = "MOL",
                            Name = "Moldova"
                        });
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.Pot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ScenarioInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioInstanceId");

                    b.ToTable("Pots");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.Scenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HomeAndAwayPerOpponent")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NumberOfGamesPerPot")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfPot")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfTeamsPerPot")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Scenarios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c5300dfa-f995-4bb3-9e2e-009b85752995"),
                            HomeAndAwayPerOpponent = false,
                            Name = "UEFA2425",
                            NumberOfGamesPerPot = 2,
                            NumberOfPot = 4,
                            NumberOfTeamsPerPot = 9
                        },
                        new
                        {
                            Id = new Guid("d5300dfa-f995-4bb3-9e2e-009b85752995"),
                            HomeAndAwayPerOpponent = true,
                            Name = "EPL",
                            NumberOfGamesPerPot = 19,
                            NumberOfPot = 1,
                            NumberOfTeamsPerPot = 20
                        },
                        new
                        {
                            Id = new Guid("92944679-54a6-4248-9bf8-e50e0774dedc"),
                            HomeAndAwayPerOpponent = false,
                            Name = "4-2-2",
                            NumberOfGamesPerPot = 2,
                            NumberOfPot = 2,
                            NumberOfTeamsPerPot = 4
                        },
                        new
                        {
                            Id = new Guid("e2e36700-16f6-44de-a5c3-6acf484655c3"),
                            HomeAndAwayPerOpponent = false,
                            Name = "3-2-4",
                            NumberOfGamesPerPot = 2,
                            NumberOfPot = 4,
                            NumberOfTeamsPerPot = 3
                        });
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.ScenarioInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("ScenarioInstances");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.Club", b =>
                {
                    b.HasOne("UEFASwissFormatSelector.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.ClubInPot", b =>
                {
                    b.HasOne("UEFASwissFormatSelector.Models.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UEFASwissFormatSelector.Models.Pot", "Pot")
                        .WithMany("ClubsInPot")
                        .HasForeignKey("PotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Pot");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.ClubInScenarioInstance", b =>
                {
                    b.HasOne("UEFASwissFormatSelector.Models.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UEFASwissFormatSelector.Models.ScenarioInstance", "ScenarioInstance")
                        .WithMany("ClubsInScenarioInstance")
                        .HasForeignKey("ScenarioInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("ScenarioInstance");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.Pot", b =>
                {
                    b.HasOne("UEFASwissFormatSelector.Models.ScenarioInstance", null)
                        .WithMany("Pots")
                        .HasForeignKey("ScenarioInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.ScenarioInstance", b =>
                {
                    b.HasOne("UEFASwissFormatSelector.Models.Scenario", "Scenario")
                        .WithMany()
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.Pot", b =>
                {
                    b.Navigation("ClubsInPot");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.ScenarioInstance", b =>
                {
                    b.Navigation("ClubsInScenarioInstance");

                    b.Navigation("Pots");
                });
#pragma warning restore 612, 618
        }
    }
}
