// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UEFASwissFormatSelector.Services;

#nullable disable

namespace UEFASwissFormatSelector.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250917102902_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UEFASwissFormatSelector.Models.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.ClubInPot", b =>
                {
                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PotId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClubId", "PotId");

                    b.HasIndex("PotId");

                    b.ToTable("ClubsInPot");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.ClubInScenarioInstance", b =>
                {
                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScenarioInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Ranking")
                        .HasColumnType("real");

                    b.HasKey("ClubId", "ScenarioInstanceId");

                    b.HasIndex("ScenarioInstanceId");

                    b.ToTable("ClubsInScenarioInstance");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbrevation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.Pot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ScenarioInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioInstanceId");

                    b.ToTable("Pots");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.Scenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HomeAndAwayPerOpponent")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NumberOfGamesPerPot")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfPot")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfTeamsPerPot")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Scenarios");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.ScenarioInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("ScenarioInstances");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.Club", b =>
                {
                    b.HasOne("UEFASwissFormatSelector.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.ClubInPot", b =>
                {
                    b.HasOne("UEFASwissFormatSelector.Models.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UEFASwissFormatSelector.Models.Pot", "Pot")
                        .WithMany("ClubsInPot")
                        .HasForeignKey("PotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Pot");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.ClubInScenarioInstance", b =>
                {
                    b.HasOne("UEFASwissFormatSelector.Models.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UEFASwissFormatSelector.Models.ScenarioInstance", "ScenarioInstance")
                        .WithMany("ClubsInScenarioInstance")
                        .HasForeignKey("ScenarioInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("ScenarioInstance");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.Pot", b =>
                {
                    b.HasOne("UEFASwissFormatSelector.Models.ScenarioInstance", null)
                        .WithMany("Pots")
                        .HasForeignKey("ScenarioInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.ScenarioInstance", b =>
                {
                    b.HasOne("UEFASwissFormatSelector.Models.Scenario", "Scenario")
                        .WithMany()
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.Pot", b =>
                {
                    b.Navigation("ClubsInPot");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.ScenarioInstance", b =>
                {
                    b.Navigation("ClubsInScenarioInstance");

                    b.Navigation("Pots");
                });
#pragma warning restore 612, 618
        }
    }
}
