// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UEFASwissFormatSelector.Services;

#nullable disable

namespace UEFASwissFormatSelector.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250917113544_MigrationToFixCOmpatibilityIssues")]
    partial class MigrationToFixCOmpatibilityIssues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UEFASwissFormatSelector.Models.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cfa6de2b-5ec8-4e62-9eb7-9a8245a9ab71"),
                            CountryId = new Guid("a5300dfa-f995-4bb3-9e2e-009b85752995"),
                            Name = "Manchester City"
                        },
                        new
                        {
                            Id = new Guid("6ad15ec8-af1f-47a2-8b84-291d93e3fb57"),
                            CountryId = new Guid("a5300dfa-f995-4bb3-9e2e-009b85752995"),
                            Name = "Liverpool"
                        },
                        new
                        {
                            Id = new Guid("ec7d906b-1f85-4534-a006-a852539d568f"),
                            CountryId = new Guid("a5300dfa-f995-4bb3-9e2e-009b85752995"),
                            Name = "Arsenal"
                        },
                        new
                        {
                            Id = new Guid("487dfe46-bca4-4019-aaae-a2dae3f6a8b4"),
                            CountryId = new Guid("a5300dfa-f995-4bb3-9e2e-009b85752995"),
                            Name = "Manchester United"
                        },
                        new
                        {
                            Id = new Guid("dbd250b3-1334-40d7-9682-13b6edec9111"),
                            CountryId = new Guid("a5300dfa-f995-4bb3-9e2e-009b85752995"),
                            Name = "Newcastle United"
                        },
                        new
                        {
                            Id = new Guid("cf7eb2aa-b192-413f-881a-81746ecf5461"),
                            CountryId = new Guid("a5300dfa-f995-4bb3-9e2e-009b85752995"),
                            Name = "West Ham United"
                        },
                        new
                        {
                            Id = new Guid("aefd829a-eccb-4c40-8fef-29ff3d239450"),
                            CountryId = new Guid("a5300dfa-f995-4bb3-9e2e-009b85752995"),
                            Name = "Aston Villa"
                        },
                        new
                        {
                            Id = new Guid("371dedc0-07a8-4bee-a68d-b40fb6c50b09"),
                            CountryId = new Guid("8bb21cd3-572c-4392-bf4d-29aa4cf58b06"),
                            Name = "Real Madrid"
                        },
                        new
                        {
                            Id = new Guid("cef7d048-b46e-49c3-829d-7abd5472254d"),
                            CountryId = new Guid("8bb21cd3-572c-4392-bf4d-29aa4cf58b06"),
                            Name = "Barcelona"
                        },
                        new
                        {
                            Id = new Guid("50461a41-d0af-436c-8956-ff3881148f88"),
                            CountryId = new Guid("8bb21cd3-572c-4392-bf4d-29aa4cf58b06"),
                            Name = "Atlético Madrid"
                        },
                        new
                        {
                            Id = new Guid("a7c222f6-7968-45dc-a419-374c3395fbe5"),
                            CountryId = new Guid("8bb21cd3-572c-4392-bf4d-29aa4cf58b06"),
                            Name = "Sevilla"
                        },
                        new
                        {
                            Id = new Guid("af156ba6-7347-4862-b2ac-e28d53a44cc7"),
                            CountryId = new Guid("8bb21cd3-572c-4392-bf4d-29aa4cf58b06"),
                            Name = "Real Sociedad"
                        },
                        new
                        {
                            Id = new Guid("1c249449-395b-47fa-a9c6-7e06a54bb338"),
                            CountryId = new Guid("8bb21cd3-572c-4392-bf4d-29aa4cf58b06"),
                            Name = "Villarreal"
                        },
                        new
                        {
                            Id = new Guid("0bac3e11-5c17-4ecb-94a9-d10f406c4162"),
                            CountryId = new Guid("6321ef33-73b5-45f8-9927-9afb37f39844"),
                            Name = "Bayern Munich"
                        },
                        new
                        {
                            Id = new Guid("1393549e-03eb-41d3-a139-dd03b25cb023"),
                            CountryId = new Guid("6321ef33-73b5-45f8-9927-9afb37f39844"),
                            Name = "Borussia Dortmund"
                        },
                        new
                        {
                            Id = new Guid("bf422d8a-ab82-4021-ba47-3b7bb2cfeeb1"),
                            CountryId = new Guid("6321ef33-73b5-45f8-9927-9afb37f39844"),
                            Name = "Bayer Leverkusen"
                        },
                        new
                        {
                            Id = new Guid("b624e4d7-211e-4d61-a41c-bbf735792ee0"),
                            CountryId = new Guid("6321ef33-73b5-45f8-9927-9afb37f39844"),
                            Name = "Union Berlin"
                        },
                        new
                        {
                            Id = new Guid("f11afe6d-1133-4c4d-b264-4cb100fb2883"),
                            CountryId = new Guid("6321ef33-73b5-45f8-9927-9afb37f39844"),
                            Name = "RB Leipzig"
                        },
                        new
                        {
                            Id = new Guid("df0f295a-b10a-4625-add3-1d0fcd29cc5f"),
                            CountryId = new Guid("5dcf05a0-aeec-487e-bab1-10a4b4913ef3"),
                            Name = "Inter Milan"
                        },
                        new
                        {
                            Id = new Guid("a7a29524-5ee0-40d0-9d6b-febb94710658"),
                            CountryId = new Guid("5dcf05a0-aeec-487e-bab1-10a4b4913ef3"),
                            Name = "Juventus"
                        },
                        new
                        {
                            Id = new Guid("898c7e94-b104-4b63-8af9-12d6c76badaf"),
                            CountryId = new Guid("5dcf05a0-aeec-487e-bab1-10a4b4913ef3"),
                            Name = "AC Milan"
                        },
                        new
                        {
                            Id = new Guid("1d72ddc1-48ba-4525-a985-5ba8eabdd366"),
                            CountryId = new Guid("5dcf05a0-aeec-487e-bab1-10a4b4913ef3"),
                            Name = "Napoli"
                        },
                        new
                        {
                            Id = new Guid("33f5a98a-467b-4ee3-950e-b1cc4c608c28"),
                            CountryId = new Guid("5dcf05a0-aeec-487e-bab1-10a4b4913ef3"),
                            Name = "Roma"
                        },
                        new
                        {
                            Id = new Guid("b081a154-33a1-4c65-b5f3-16c749626710"),
                            CountryId = new Guid("5dcf05a0-aeec-487e-bab1-10a4b4913ef3"),
                            Name = "Lazio"
                        },
                        new
                        {
                            Id = new Guid("da42e4b3-0a01-43df-9dcc-54885a2bfb27"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39844"),
                            Name = "Olympique de Marseille"
                        },
                        new
                        {
                            Id = new Guid("c878cb97-9037-49b7-a29b-7f8b2f417502"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39844"),
                            Name = "Paris Saint-Germain"
                        },
                        new
                        {
                            Id = new Guid("bb0e19b0-0f94-450f-89b1-1c4215e71dd3"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39844"),
                            Name = "Lyon"
                        },
                        new
                        {
                            Id = new Guid("f19d9e88-9a7a-4d23-8dfc-51607a7fdf77"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39844"),
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = new Guid("d4b5ae48-cc4e-4c81-829a-6638390e80b3"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39855"),
                            Name = "Benfica"
                        },
                        new
                        {
                            Id = new Guid("630d4609-9688-4600-a904-cfbc637368bc"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39855"),
                            Name = "Porto"
                        },
                        new
                        {
                            Id = new Guid("0eabb8e5-a79d-457c-8905-3639cb5196a2"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39855"),
                            Name = "Sporting CP"
                        },
                        new
                        {
                            Id = new Guid("aa3536b2-ceb2-4c1d-9083-0b2d3cca69d5"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39866"),
                            Name = "Ajax"
                        },
                        new
                        {
                            Id = new Guid("bf9ea561-c896-47cd-9eee-45499a3da63a"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39866"),
                            Name = "Feyenoord"
                        },
                        new
                        {
                            Id = new Guid("4fffd503-4986-4e70-ba74-2cc3dc6e66e2"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39877"),
                            Name = "Celtic"
                        },
                        new
                        {
                            Id = new Guid("9bd0a45d-17c6-4aaf-86ad-93b84eb1e0c1"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39888"),
                            Name = "Shakhtar Donetsk"
                        },
                        new
                        {
                            Id = new Guid("0908321e-4eb5-40ef-b3da-fe157d3e3c58"),
                            CountryId = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39899"),
                            Name = "Galatasaray"
                        },
                        new
                        {
                            Id = new Guid("6289276c-c2a4-4c0c-a35c-90e30eabeba1"),
                            CountryId = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39866"),
                            Name = "Red Star Belgrade"
                        },
                        new
                        {
                            Id = new Guid("2588ff35-1311-44d0-a148-2606b0228c83"),
                            CountryId = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39877"),
                            Name = "Dinamo Zagreb"
                        },
                        new
                        {
                            Id = new Guid("16e2aa1d-4903-48f0-b44b-560f69956c18"),
                            CountryId = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39888"),
                            Name = "Olympiacos"
                        },
                        new
                        {
                            Id = new Guid("cf500bbd-15e0-48b5-8ede-5b988bc344d9"),
                            CountryId = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39899"),
                            Name = "Club Brugge"
                        },
                        new
                        {
                            Id = new Guid("21ec319b-09a5-4f80-82f7-ac9ec33be94a"),
                            CountryId = new Guid("2661ef33-73b5-45f8-9927-9bfb37f39899"),
                            Name = "Copenhagen"
                        },
                        new
                        {
                            Id = new Guid("9001e991-ad25-4847-9df4-c462c4e9d040"),
                            CountryId = new Guid("1691ef33-73b5-45f8-9927-9bfb37f39899"),
                            Name = "Red Bull Salzburg"
                        },
                        new
                        {
                            Id = new Guid("7b53c50c-7747-4c65-b62e-a7193d3b1884"),
                            CountryId = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39899"),
                            Name = "Genk"
                        },
                        new
                        {
                            Id = new Guid("f20d7598-0db2-4222-a8fe-24fff02a0856"),
                            CountryId = new Guid("1961ef33-73b5-45f8-9927-9bfb37f39899"),
                            Name = "Sheriff Tiraspol"
                        });
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.ClubInPot", b =>
                {
                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PotId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClubId", "PotId");

                    b.HasIndex("PotId");

                    b.ToTable("ClubsInPot");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.ClubInScenarioInstance", b =>
                {
                    b.Property<Guid>("ClubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScenarioInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Ranking")
                        .HasColumnType("real");

                    b.HasKey("ClubId", "ScenarioInstanceId");

                    b.HasIndex("ScenarioInstanceId");

                    b.ToTable("ClubsInScenarioInstance");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbrevation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a5300dfa-f995-4bb3-9e2e-009b85752995"),
                            Abbrevation = "ENG",
                            Name = "England"
                        },
                        new
                        {
                            Id = new Guid("5dcf05a0-aeec-487e-bab1-10a4b4913ef3"),
                            Abbrevation = "ITA",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = new Guid("8bb21cd3-572c-4392-bf4d-29aa4cf58b06"),
                            Abbrevation = "ESP",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = new Guid("6321ef33-73b5-45f8-9927-9afb37f39844"),
                            Abbrevation = "GER",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39844"),
                            Abbrevation = "FRA",
                            Name = "France"
                        },
                        new
                        {
                            Id = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39855"),
                            Abbrevation = "POR",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39866"),
                            Abbrevation = "NED",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39877"),
                            Abbrevation = "SCO",
                            Name = "Scotland"
                        },
                        new
                        {
                            Id = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39888"),
                            Abbrevation = "UKR",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = new Guid("6661ef33-73b5-45f8-9927-9bfb37f39899"),
                            Abbrevation = "TUR",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39866"),
                            Abbrevation = "SRB",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39877"),
                            Abbrevation = "CRO",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39888"),
                            Abbrevation = "GRE",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = new Guid("1661ef33-73b5-45f8-9927-9bfb37f39899"),
                            Abbrevation = "BEL",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = new Guid("2661ef33-73b5-45f8-9927-9bfb37f39899"),
                            Abbrevation = "DEN",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = new Guid("1691ef33-73b5-45f8-9927-9bfb37f39899"),
                            Abbrevation = "BEL",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = new Guid("1961ef33-73b5-45f8-9927-9bfb37f39899"),
                            Abbrevation = "MOL",
                            Name = "Moldova"
                        });
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.Pot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ScenarioInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioInstanceId");

                    b.ToTable("Pots");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.Scenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HomeAndAwayPerOpponent")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NumberOfGamesPerPot")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfPot")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfTeamsPerPot")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Scenarios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c5300dfa-f995-4bb3-9e2e-009b85752995"),
                            HomeAndAwayPerOpponent = false,
                            Name = "UEFA2425",
                            NumberOfGamesPerPot = 2,
                            NumberOfPot = 4,
                            NumberOfTeamsPerPot = 9
                        },
                        new
                        {
                            Id = new Guid("d5300dfa-f995-4bb3-9e2e-009b85752995"),
                            HomeAndAwayPerOpponent = true,
                            Name = "EPL",
                            NumberOfGamesPerPot = 19,
                            NumberOfPot = 1,
                            NumberOfTeamsPerPot = 20
                        },
                        new
                        {
                            Id = new Guid("92944679-54a6-4248-9bf8-e50e0774dedc"),
                            HomeAndAwayPerOpponent = false,
                            Name = "4-2-2",
                            NumberOfGamesPerPot = 2,
                            NumberOfPot = 2,
                            NumberOfTeamsPerPot = 4
                        },
                        new
                        {
                            Id = new Guid("e2e36700-16f6-44de-a5c3-6acf484655c3"),
                            HomeAndAwayPerOpponent = false,
                            Name = "3-2-4",
                            NumberOfGamesPerPot = 2,
                            NumberOfPot = 4,
                            NumberOfTeamsPerPot = 3
                        });
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.ScenarioInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("ScenarioInstances");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.Club", b =>
                {
                    b.HasOne("UEFASwissFormatSelector.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.ClubInPot", b =>
                {
                    b.HasOne("UEFASwissFormatSelector.Models.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UEFASwissFormatSelector.Models.Pot", "Pot")
                        .WithMany("ClubsInPot")
                        .HasForeignKey("PotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Pot");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.ClubInScenarioInstance", b =>
                {
                    b.HasOne("UEFASwissFormatSelector.Models.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UEFASwissFormatSelector.Models.ScenarioInstance", "ScenarioInstance")
                        .WithMany("ClubsInScenarioInstance")
                        .HasForeignKey("ScenarioInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("ScenarioInstance");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.Pot", b =>
                {
                    b.HasOne("UEFASwissFormatSelector.Models.ScenarioInstance", null)
                        .WithMany("Pots")
                        .HasForeignKey("ScenarioInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.ScenarioInstance", b =>
                {
                    b.HasOne("UEFASwissFormatSelector.Models.Scenario", "Scenario")
                        .WithMany()
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.Pot", b =>
                {
                    b.Navigation("ClubsInPot");
                });

            modelBuilder.Entity("UEFASwissFormatSelector.Models.ScenarioInstance", b =>
                {
                    b.Navigation("ClubsInScenarioInstance");

                    b.Navigation("Pots");
                });
#pragma warning restore 612, 618
        }
    }
}
